server:
  port: 9999
  
spring:
  application:
    name: zuul-gateway
    
zuul:
  prefix: /api
  routes:
    greeting: 
      path: /greeting/**
      serviceId: say-hello    

ribbon:
  eureka:
    enabled: true

